spring:
  application:
    name:server
  datasource:
    url: ${DATASOURCE_URL}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  security:
    user:
      name: ${SECURITY_NAME}
      password: ${SECURITY_PASSWORD}