spring:
  application:
    name:server
  datasource:
    url: ${DATASOURCE_URL}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  security:
    user:
      name: ${SECURITY_NAME}
      password: ${SECURITY_PASSWORD}
  session:
    jdbc:
      initialize-schema: always
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true